### PR TITLE
Incorrect Course Title

### LINKED ISSUE #23: incorrect course title
course name incorrect for some courses. 

example: see [CS 4973](https://search2-beta.vercel.app/catalog/202610/CS%204973?subj=CS), this should be called 'Topics in Computer Science'

AC: correct course name

===
HINT - the scraper currently uses the name of the first section as the name of the course (see line 168 of `scrape.ts`)
docs for the relevant Banner API [endpoint here](https://search2-beta.vercel.app/docs/banner-api/search-results/Class%20Details)

### PR DESCRIPTION
**Pull request by ItsEricSun**
Went over this during stand up, but implementation essentially copied from getCourseDescription. Ran the scraper, which correctly added all the course names to the prod DB. Looks good to me!

closes #23

### CODE REVIEW

File: src/scraper/scrape.ts [hunk 1]
```diff
@@ -167,14 +209,14 @@ export async function getCourseDescriptions(courses: Course[]) {
 // arrangeCourses takes the raw sections scraped from banner and
 // pulls out the courses, arranging the sections in those courses,
 // pulls out the right fields, etc.
-export function arrangeCourses(sections: BannerSection[]) {
+export async function arrangeCourses(sections: BannerSection[]) {
```
Comment (mehallhm) [inline src/scraper/scrape.ts]: since you are no longer fetching the data in this function, you should make it synchronous again

**Review by mehallhm — CHANGES_REQUESTED** [review]

**Review by mehallhm — APPROVED** [review]

**Review by Aaryan1203 — APPROVED** [review]
