### PR TITLE
Finished fixing search bar on smaller screens; enter now required for…

### LINKED ISSUE #118: search bar on course page should "search" on enter when on mobile

### PR DESCRIPTION
**Pull request by lukej1138**
… search

# Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation, context, or
screenshots for frontend changes.

I finished updating the search bar so that on smaller screens, the user needs to press enter in order to search. Additionally, on mobile, if a user runs a search then the course cards list is displayed regardless of where they are on the catalog.

Closes 188 [https://github.com/sandboxnu/searchneu/issues/118]

## Type of Change

Please tick the boxes that best match your changes.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a PCP (ie changes in deps, database, infrastructure, or package exports)

## Testing

Please describe how you tested this PR (both manually and with tests) Provide instructions so we can reproduce.

- [ x ] Ran website and tested on mobile/large screens, worked well

## Checklist

- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code where needed
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have run a build for the entire monorepo
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] All commits are atomic and my branch is cleaned (no WIP commits)

### CODE REVIEW

File: apps/searchneu/components/catalog/MobileWrapper.tsx [hunk 1]
```diff
@@ -2,10 +2,10 @@
 
 import { SearchPanel } from "./search/FilterBar";
 import { GroupedTerms, Subject } from "@/lib/types";
-import { useParams } from "next/navigation";
+import { useParams, useSearchParams } from "next/navigation";
 import dynamic from "next/dynamic";
 import { SearchBar } from "./search/SearchBar";
-import { type ReactNode } from "react";
+import { useEffect, useState, useRef, type ReactNode } from "react";
```
Comment (mehallhm) [inline apps/searchneu/components/catalog/MobileWrapper.tsx]: this `useRef` does not look like it is used anywhere...?

**Review by Aaryan1203 — APPROVED** [review]
